{
 "title": "Farmer Enrollment Insights",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(app_farmer_total, region)"
    }
   },
   {
    "name": "province",
    "query": {
     "query": "label_values(app_farmer_total{region=~\"$region\"}, province)"
    }
   },
   {
    "name": "municity",
    "label": "municipality-city",
    "query": {
     "query": "label_values(app_farmer_total{region=~\"$region\", province=~\"$province\"}, municity)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. of farmers per region",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (app_farmer_total{region=~\"$region\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. of farmers per province",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, province) (app_farmer_total{region=~\"$region\", province=~\"$province\"})",
     "legendFormat": "{{region}}, {{province}}"
    }
   ]
  },
  {
   "title": "No. of farmers per municipality or city",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, province, municity) (app_farmer_total{region=~\"$region\", province=~\"$province\", municity=~\"$municity\"})",
     "legendFormat": "{{municity}}"
    }
   ]
  },
  { "title": "Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "No. of farmers per region",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(region) (app_farmer_total{region=~\"$region\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. of farmers per province",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(region, province) (app_farmer_total{region=~\"$region\", province=~\"$province\"})",
     "legendFormat": "{{region}}, {{province}}"
    }
   ]
  },
  {
   "title": "No. of farmers per municipality or city",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(region, province, municity) (app_farmer_total{region=~\"$region\", province=~\"$province\", municity=~\"$municity\"})",
     "legendFormat": "{{municity}}"
    }
   ]
  }
 ]
}