{
 "title": "Farmer Report Insights",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(app_farmer_report_estimated_yield_grams, region)"
    }
   },
   {
    "name": "province",
    "query": {
     "query": "label_values(app_farmer_report_estimated_yield_grams{region=~\"$region\"}, province)"
    }
   },
   {
    "name": "municity",
    "label": "municipality-city",
    "query": {
     "query": "label_values(app_farmer_report_estimated_yield_grams{region=~\"$region\", province=~\"$province\"}, municity)"
    }
   },
   {
    "name": "crop",
    "query": {
     "query": "label_values(app_farmer_report_estimated_yield_grams, crop)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estimated kilogram yield per region",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, crop, yield_date_earliest, yield_date_latest) (app_farmer_report_estimated_yield_grams{region=~\"$region\", crop=~\"$crop\"}) / 1000",
     "legendFormat": "{{region}} - {{crop}} ({{yield_date_earliest}} to {{yield_date_latest}})"
    }
   ]
  },
  {
   "title": "Estimated kilogram yield per province",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, province, crop, yield_date_earliest, yield_date_latest) (app_farmer_report_estimated_yield_grams{region=~\"$region\", province=~\"$province\", crop=~\"$crop\"}) / 1000",
     "legendFormat": "{{province}} - {{crop}} ({{yield_date_earliest}} to {{yield_date_latest}})"
    }
   ]
  },
  {
   "title": "Estimated kilogram yield per municipality or city",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, province, municity, crop, yield_date_earliest, yield_date_latest) (app_farmer_report_estimated_yield_grams{region=~\"$region\", province=~\"$province\", municity=~\"$municity\", crop=~\"$crop\"}) / 1000",
     "legendFormat": "{{municity}} - {{crop}} ({{yield_date_earliest}} to {{yield_date_latest}})"
    }
   ]
  },
  { "title": "Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Estimated kilogram yield per region",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum by(region, crop, yield_date_earliest, yield_date_latest) (app_farmer_report_estimated_yield_grams{region=~\"$region\", crop=~\"$crop\"}) / 1000",
     "legendFormat": "{{region}} - {{crop}} ({{yield_date_earliest}} to {{yield_date_latest}})"
    }
   ]
  },
  {
   "title": "Estimated kilogram yield per province",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum by(region, province, crop, yield_date_earliest, yield_date_latest) (app_farmer_report_estimated_yield_grams{region=~\"$region\", province=~\"$province\", crop=~\"$crop\"}) / 1000",
     "legendFormat": "{{province}} - {{crop}} ({{yield_date_earliest}} to {{yield_date_latest}})"
    }
   ]
  },
  {
   "title": "Estimated kilogram yield per municipality or city",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "sum by(region, province, municity, crop, yield_date_earliest, yield_date_latest) (app_farmer_report_estimated_yield_grams{region=~\"$region\", province=~\"$province\", municity=~\"$municity\", crop=~\"$crop\"}) / 1000",
     "legendFormat": "{{municity}} - {{crop}} ({{yield_date_earliest}} to {{yield_date_latest}})"
    }
   ]
  }
 ]
}