{
 "title": "Seed Allocation Insights",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(app_batch_seed_allocation_total, region)"
    }
   },
   {
    "name": "province",
    "query": {
     "query": "label_values(app_batch_seed_allocation_total{region=~\"$region\"}, province)"
    }
   },
   {
    "name": "municity",
    "label": "municipality-city",
    "query": {
     "query": "label_values(app_batch_seed_allocation_total{region=~\"$region\", province=~\"$province\"}, municity)"
    }
   },
   {
    "name": "crop",
    "query": {
     "query": "label_values(app_batch_seed_allocation_total, crop)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. of seed allocations per region",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, crop) (app_batch_seed_allocation_total{region=~\"$region\", crop=~\"$crop\"})",
     "legendFormat": "{{region}} - {{crop}}"
    }
   ]
  },
  {
   "title": "No. of seed allocations per province",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, province, crop) (app_batch_seed_allocation_total{region=~\"$region\", province=~\"$province\", crop=~\"$crop\"})",
     "legendFormat": "{{province}} - {{crop}}"
    }
   ]
  },
  {
   "title": "No. of seed allocations per municipality or city",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, province, municity, crop) (app_batch_seed_allocation_total{region=~\"$region\", province=~\"$province\", municity=~\"$municity\", crop=~\"$crop\"})",
     "legendFormat": "{{municity}} - {{crop}}"
    }
   ]
  },
  { "title": "Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "No. of seeds allocations per region",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(region, crop) (app_batch_seed_allocation_total{region=~\"$region\", crop=~\"$crop\"})",
     "legendFormat": "{{region}} - {{crop}}"
    }
   ]
  },
  {
   "title": "No. of seed allocations per province",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(region, province, crop) (app_batch_seed_allocation_total{region=~\"$region\", province=~\"$province\", crop=~\"$crop\"})",
     "legendFormat": "{{province}} - {{crop}}"
    }
   ]
  },
  {
   "title": "No. of seed allocations per municipality or city",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(region, province, municity, crop) (app_batch_seed_allocation_total{region=~\"$region\", province=~\"$province\", municity=~\"$municity\", crop=~\"$crop\"})",
     "legendFormat": "{{municity}} - {{crop}}"
    }
   ]
  }
 ]
}