{
 "title": "Site Insights",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(app_province_total, region)"
    }
   },
   {
    "name": "province",
    "query": {
     "query": "label_values(app_municipality_city_total{region=~\"$region\"}, province)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. of site regions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (app_region_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. of site provinces per region",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (app_province_total{region=~\"$region\"})",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "No. of site municipalities or cities per province",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, province, municity) (app_municipality_city_total{region=~\"$region\", province=~\"$province\"})",
     "legendFormat": "{{province}}"
    }
   ]
  },
  { "title": "Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "No. of site regions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(region) (app_region_total)",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "No. of site provinces per region",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(region, province) (app_province_total{region=~\"$region\"})",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "No. of site municipalities or cities per province",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(region, province, municity) (app_municipality_city_total{region=~\"$region\", province=~\"$province\"})",
     "legendFormat": "{{province}}"
    }
   ]
  }
 ]
}